"""Swagger 请求和返回字段的通俗中文含义。"""

from __future__ import annotations

FIELD_MEANINGS = {
    "acked_sequence": "已经确认收到的最大事件顺序号。",
    "action": "要执行或选择的操作。",
    "action_args": "传给设备动作的参数。",
    "action_name": "设备动作名称。",
    "action_type": "设备动作的数据类型。",
    "actual_change_set": "转运失败后现场确认的实际物料变化。",
    "actor": "产生这条记录的操作方。",
    "aggregate_id": "这条事件所属对象的编号。",
    "aggregate_type": "这条事件所属对象的类型。",
    "aggregate_version": "这条事件对应的对象版本号。",
    "aliases": "该试剂的其他名称。",
    "amounts_json": "各成分及其数量。",
    "applied_graph": "已经应用的工作流图。",
    "attempt": "当前是第几次尝试。",
    "available_sites": "该资源允许使用的库位。",
    "backend_task_uuid": "上游系统中任务的唯一编号（UUID）。",
    "barcode": "物料或试剂条码。",
    "batch_no": "批次号。",
    "breakpoint_node_uuids": "运行到这些节点前暂停。",
    "cancel_reason": "取消入库预留的原因。",
    "canceled_at": "取消时间。",
    "candidate_hash": "待应用内容的校验值，用来确认应用的是刚才检查过的内容。",
    "candidate_site_uuids": "允许放入的候选库位唯一编号列表。",
    "carrier_material_uuid": "承载该试剂或样品的物料唯一编号（UUID）。",
    "cas": "化合物的登记号（CAS 号）。",
    "category": "所属类别。",
    "causation_id": "直接导致这条记录的命令或事件编号。",
    "child_uuid": "子物料的唯一编号（UUID）。",
    "class": "资源在程序中的类名。",
    "cloud_uuid": "上游系统中的唯一编号（UUID）。",
    "code": "接口结果码。0 通常表示成功，其他值表示失败或需要处理。",
    "command_id": "库存命令编号。",
    "commands": "库存命令列表。",
    "comment": "处理人填写的备注。",
    "components": "样品包含的成分。",
    "concentration_unit": "浓度单位。",
    "concentration_value": "浓度数值。",
    "config": "资源配置。",
    "config_info": "资源配置详情。",
    "confirmed_by": "完成人工确认的人员或系统名称。",
    "content": "库存实例中保存的内容。",
    "contents": "库存内容列表。",
    "contract_uuid": "要插入的子工作流定义唯一编号（UUID）。",
    "cover": "资源封面图片地址。",
    "create_time": "创建时间。",
    "created_at": "创建时间。",
    "ctx": "参数错误的补充信息。",
    "cursor_name": "同步进度名称。",
    "cursors": "库存同步进度列表。",
    "data": "接口返回或请求携带的具体内容。",
    "deadline": "任务最晚开始或完成时间。",
    "delta_json": "本次库存数量变化。",
    "depth": "对象在物料关系中的层级。",
    "description": "用途或补充说明。",
    "density_g_per_ml": "密度，单位为克每毫升。",
    "detail": "参数错误明细列表。",
    "device_bindings": "子工作流中的设备选择。",
    "device_command_id": "设备端命令编号。",
    "device_id": "设备编号。",
    "device_params": "设备初始化参数。",
    "disabled": "是否禁止执行该节点。",
    "dispatch_block_reason": "当前不能向设备下发任务的原因。",
    "display_name": "页面上显示的名称。",
    "edge_id": "当前边缘运行实例编号。",
    "edge_uuid": "库存实例的唯一编号（UUID）。",
    "edge_uuids": "要删除的连线唯一编号列表。",
    "edges": "工作流连线列表。",
    "entries": "库存变更流水列表。",
    "entry_uuid": "入库记录的唯一编号（UUID）。",
    "error": "错误详情。",
    "error_code": "错误类型代码。",
    "event_id": "事件编号。",
    "event_type": "事件类型。",
    "events": "事件列表。",
    "execution_policy": "节点执行时使用的重试、超时等设置。",
    "expected_draft_hash": "调用方当前看到的草稿校验值，用于防止覆盖别人的新修改。",
    "expected_revision": "调用方当前看到的修改版本号，用于防止覆盖新修改。",
    "expected_version": "调用方当前看到的版本号，用于防止覆盖新修改。",
    "expected_workflow_revision": "调用方当前看到的工作流修改版本号。",
    "expires_at": "入库预留过期时间。",
    "expiry": "有效期或过期时间。",
    "footer": "节点卡片底部显示的文字。",
    "graph": "工作流完整图。",
    "handles": "节点可连接的输入和输出。",
    "has_more": "是否还有下一页。",
    "hold_uuid": "调试暂停点的唯一编号（UUID）。",
    "icon": "页面上显示的图标。",
    "id": "对象编号。",
    "idempotency_key": "本次操作的唯一键；相同键重复提交时不会重复处理。",
    "inchi_key": "化合物的 InChIKey。",
    "init_param_schema": "设备初始化参数的格式说明。",
    "input": "工作流入口参数。",
    "instance_uuid": "库存实例的唯一编号（UUID）。",
    "instances": "库存实例列表。",
    "inventory_bindings": "工作流运行时选择的具体库存。",
    "inventory_requirements": "工作流所需的库存条件。",
    "inventory_type": "选择的库存类型。",
    "inventory_uuid": "选择的库存唯一编号（UUID）。",
    "invocation_key": "本次工站调用的唯一键；用于避免重复创建任务。",
    "invocation_uuid": "本次子工作流调用的唯一编号（UUID）；不填写时由服务生成。",
    "items": "当前返回的记录列表。",
    "jobId": "设备任务编号。",
    "job_id": "设备任务编号。",
    "kind": "记录类型。",
    "lab_id": "实验室编号。",
    "launch_overrides": "设备启动时临时覆盖的参数。",
    "ledger_id": "库存变更流水编号。",
    "legacy_cloud_id": "旧上游系统使用的编号。",
    "length": "外形长度。",
    "loc": "参数错误所在的位置。",
    "lot_id": "库存批次编号。",
    "lots": "库存批次列表。",
    "material_uuid": "物料的唯一编号（UUID）。",
    "max_sequence": "当前最大的事件顺序号。",
    "message": "接口结果说明。",
    "meta_data": "调用方需要额外保存的信息。",
    "minimized": "节点在编辑器中是否折叠显示。",
    "model": "资源使用的模型信息。",
    "molecular_formula": "化学分子式。",
    "molecular_weight": "相对分子质量。",
    "mount_uuid": "物料挂载位置的唯一编号（UUID）。",
    "msg": "错误原因。",
    "name": "名称。",
    "name_en": "英文名称。",
    "new_total": "库存变更后的总数量。",
    "node_id": "工作流节点编号。",
    "node_requirements": "各工作流节点的库存需求。",
    "node_uuids": "要删除的节点唯一编号列表。",
    "nodes": "工作流节点列表。",
    "normalized_input": "服务检查并整理后的工作流入口参数。",
    "notebook_id": "关联的实验记录编号。",
    "observed_at": "实际观察到该状态的时间。",
    "occurred_at": "事件发生时间。",
    "online": "设备当前是否在线。",
    "op_type": "库存变更操作类型。",
    "operation_category_uuid": "实验操作类别的唯一编号（UUID）。",
    "option": "选择的错误处理方式及其附加内容。",
    "option_id": "选择的处理方式编号。",
    "page": "当前页码。",
    "page_size": "每页数量。",
    "param": "节点、动作或子工作流使用的参数。",
    "parent_uuid": "父节点或父物料的唯一编号（UUID）。",
    "payload": "事件或命令携带的内容。",
    "payload_json": "事件或命令携带的 JSON 内容。",
    "physical_state": "试剂的物理状态。",
    "pose": "节点在编辑器中的位置和显示信息。",
    "position_x": "三维位置的 X 坐标。",
    "position_y": "三维位置的 Y 坐标。",
    "position_z": "三维位置的 Z 坐标。",
    "preflight_hash": "本次运行检查结果的校验值。",
    "priority": "任务优先级。high 比 normal 优先。",
    "processed_at": "命令处理完成时间。",
    "properties": "设备属性名称和对应的最新值。",
    "python_source": "工作流的 Python 源码。",
    "quantity": "数量。",
    "quantity_available": "当前可用数量。",
    "quantity_delta": "本次增加或减少的数量。",
    "quantity_reserved": "已经预留的数量。",
    "quantity_total": "库存总数量。",
    "quantity_unit": "数量单位。",
    "quarantined": "该库存是否已被隔离，隔离后不能正常分配。",
    "reason": "操作原因或补充说明。",
    "received_at": "确认收货时间。",
    "reagent": "试剂库存详情。",
    "reagent_info_uuid": "试剂信息的唯一编号（UUID）。",
    "reagent_uuid": "试剂库存的唯一编号（UUID）。",
    "registry_type": "资源在领域包中登记的类型。",
    "relation": "该库存实例与其他物料的关系。",
    "relations": "库存关系列表。",
    "relative_position": "物料相对父物料的位置。",
    "replayed": "本次结果是否来自之前相同命令的缓存。",
    "requirement_key": "工作流中这项库存需求的名称。",
    "reservation_id": "库存预留编号。",
    "reservations": "库存预留列表。",
    "reserved_quantity": "本次为工作流预留的数量。",
    "resource_template_uuid": "资源模板的唯一编号（UUID）。",
    "resources": "资源模板列表。",
    "resolution": "对不确定任务的最终判断。",
    "result": "操作结果。",
    "result_json": "操作结果的 JSON 内容。",
    "ret_value": "设备任务返回的内容。",
    "revision": "当前修改版本号。",
    "revision_fingerprint": "工作流当前内容的校验值。",
    "rotation_x": "绕 X 轴的旋转角度。",
    "rotation_y": "绕 Y 轴的旋转角度。",
    "rotation_z": "绕 Z 轴的旋转角度。",
    "run_mode": "工作流运行方式。",
    "sample_material": "动作参数中样品编号与物料唯一编号的对应关系。",
    "scale_x": "三维模型在 X 方向的缩放比例。",
    "scale_y": "三维模型在 Y 方向的缩放比例。",
    "scale_z": "三维模型在 Z 方向的缩放比例。",
    "scene": "实验室三维场景信息。",
    "scope": "调试命令影响的范围。",
    "script": "节点执行的脚本内容。",
    "sequence": "事件顺序号。",
    "server_info": "任务来源和发送时间等信息。",
    "site_placement": "把物料放入库位或从库位取出的操作。",
    "site_uuid": "库位的唯一编号（UUID）。",
    "slot_id": "库位中的槽位编号。",
    "slot_uuids": "占用的槽位唯一编号列表。",
    "smiles": "化合物的 SMILES 结构式。",
    "snapshot_sequence": "生成库存快照时的事件顺序号。",
    "source": "状态或数据的来源。",
    "source_handle_uuid": "连线起点输出口的唯一编号（UUID）。",
    "source_node_uuid": "连线起点节点的唯一编号（UUID）。",
    "source_uri": "资源来源地址。",
    "span_id": "一次调用中的步骤跟踪编号。",
    "spec": "提交时使用的工作流定义。",
    "spec_json": "提交时使用的工作流定义 JSON。",
    "start_node_uuids": "调试运行的起始节点唯一编号列表。",
    "state": "当前状态。",
    "state_data": "物料状态的具体内容。",
    "state_json": "状态的 JSON 内容。",
    "status": "当前状态。",
    "subject_type": "摆放对象的类型。",
    "suc_type": "设备任务的完成方式，例如正常完成、跳过或人工处理。",
    "success": "设备任务是否执行成功。",
    "tags": "用于搜索和分类的标签。",
    "target_handle_uuid": "连线终点输入口的唯一编号（UUID）。",
    "target_node_uuid": "连线终点或任务控制目标节点的唯一编号（UUID）。",
    "task_id": "工作流任务编号。",
    "task_uuid": "工作流任务的唯一编号（UUID）。",
    "template_id": "库存模板编号。",
    "templates": "库存模板列表。",
    "trace_id": "一次完整请求的跟踪编号。",
    "traceparent": "跨服务传递的请求跟踪信息。",
    "tracestate": "跨服务传递的补充跟踪信息。",
    "transport_started_at": "物料开始运输的时间。",
    "ttl_seconds": "入库预留从创建起的有效秒数。",
    "type": "类型。",
    "unit": "数量单位。",
    "unknown_command_ids": "设备端状态未知的命令编号列表。",
    "update_time": "最后更新时间。",
    "updated_at": "最后更新时间。",
    "uuid": "对象的唯一编号（UUID）。",
    "uuids": "要查询的物料唯一编号列表。",
    "version": "当前版本号。",
    "warehouse_zone_id": "所在实验室区域编号。",
    "width": "外形宽度。",
    "with_children": "是否同时返回子物料。",
    "workflow_id": "工作流定义或一次运行的编号。",
    "workflow_name": "工作流名称。",
    "workflow_node_job_uuid": "节点任务的唯一编号（UUID）。",
    "workflow_node_template_uuid": "工作流节点模板的唯一编号（UUID）。",
    "workflow_task_uuid": "工作流任务的唯一编号（UUID）。",
    "workflow_type": "工作流类型：normal 是普通工作流，experiment_operation 是实验操作。",
    "workflow_uuid": "工作流或实验操作的唯一编号（UUID）。",
}


SCHEMA_FIELD_MEANINGS = {
    ("BackendErrorDetail", "code"): "更具体的错误类型；只有部分错误会返回。",
    ("DebugCommandScope", "type"): "调试命令控制的范围类型。",
    ("DebugWorkflowTaskCommandRequest", "type"): "调试控制命令类型。",
    ("ErrorDecisionIn", "action"): "处理方式，例如重试、跳过或终止。",
    ("ErrorDecisionIn", "result"): "需要人工补充时提交的处理结果。",
    ("JobAddReq", "action"): "要执行的设备动作名称。",
    ("JobAddReq", "data"): "设备动作使用的其他数据。",
    ("JobData", "result"): "任务结束后返回的设备执行结果。",
    ("JobData", "status"): "设备任务状态：0 未知、1 已接受、2 执行中、3 正在取消、4 成功、5 已取消、6 失败。",
    ("ManualConfirmationDecisionRequest", "action"): "人工确认的处理方式。",
    ("OperationCategoryReadModel", "uuid"): "实验操作类别的唯一编号（UUID）。",
    ("ValidationError", "input"): "导致参数校验失败的原始值。",
    ("ValidationError", "type"): "参数错误类型。",
    ("WorkflowNodeCreateRequest", "type"): "节点类型。",
    ("WorkflowEdgeWrite", "uuid"): "工作流连线的唯一编号（UUID）。",
    ("WorkflowNodeWrite", "uuid"): "工作流节点的唯一编号（UUID）。",
    ("WorkflowNodeWrite", "status"): "节点当前状态。",
    ("WorkflowNodeWrite", "type"): "节点类型。",
    ("WorkflowReadModel", "status"): (
        "工作流状态：source 表示尚未发布，published 表示已经发布并可供其他工作流使用。"
    ),
    ("WorkflowReadModel", "uuid"): "工作流或实验操作的唯一编号（UUID）。",
    ("WorkflowTaskCommandRequest", "type"): "任务控制命令类型。",
}
